### PR TITLE
Tournament RESTFul

### PR DESCRIPTION
**Pull request by ysasgon**
Pull request to merge the devRestFran branch into the testing branch. This branch has the RESTFul web service class of the Tournament entity.

### CODE REVIEW

**Comment by Javier-Fermin** [comment]
Thanks Imanol for fixing the conflict, everything seems fine now.

**Comment by PerezImanol** [comment]
Conflicts resolved, minor import changes and some logic, I think we are done

**Comment by mlnnzr** [comment]
it's fine, i don't dee any issue

**Comment by ysasgon** [comment]
Great job Imanol for fixing all the conflicts so we can merge.

**Pull request merged**
